### ISSUE TITLE
Link or copy the local builds info for LFRic Apps to the Working Practices docs?

### ISSUE THREAD

**Issue by astroDimitrios** [MetOffice/simulation-systems#183]
I was looking in the working practices docs on how to build locally and could only find info on running the test-suites for LFRic Apps.

Could the [local build wiki page](https://code.metoffice.gov.uk/trac/lfric_apps/wiki/local_builds) be linked or added to these working practice docs?

**Comment by jennyhickson** [comment]
Good plan. Will include a link.
