### ISSUE TITLE
Clarify testing expectations

### ISSUE THREAD

**Issue by jennyhickson** [MetOffice/simulation-systems#61]
Question asked about when testing JULES with the UM which groups are required - is it developer or just jules. This could be made clearer in the docs. 

I would suggest in the Testing JULES page to add details of testing expectations and a link to the working with multi repositories page for the instructions. Probably the same for UKCA.

**Comment by richardgilham** [comment]
I think the testing expectations for KGO changes for all repos could do with being made more obvious
