### ISSUE TITLE
Error in writing xios diagnostics in gungho_model

### ISSUE THREAD

**Issue by dennissergeev** [MetOffice/simulation-systems#78]
I was wondering if anyone could help me with the XIOS error that I get in a `gungho_model` run please.

The xios log files contain this message:
```
In file "onetcdf4_impl.hpp", function "void xios::CONetCDF4::writeData(const xios::CArray<T, ndim> &, const std::basic_string<char, std::char_traits<char>, std::allocator<char>> &, bool, unsigned long, const std::vector<unsigned long, std::allocator<unsigned long>> *, const std::vector<unsigned long, std::allocator<unsigned long>> *) [with T = int, ndim = 2]",  line 36 -> [ input array size = 310, intern array size = 256 ] Invalid input data !
```

I don't understand why it crashes and why it does it on the 2nd CRUN (the 1st runs OK). The diagnostic frequency is 720 and the run length is also 720 time steps. The output stream is `lfric_diag.nc`. I'm running this as part of a rose-stem suite on Monsoon. Happy to provide more details.

**Comment by jennyhickson** [comment]
Hi Dennis - the issues in this repository aren't being used to track LFRic problems - you'll probably have a better chance of someone answering your query in the LFRic discussion group here https://github.com/MetOffice/simulation-systems/discussions/categories/lfric.

Hope that helps
