### ISSUE TITLE
converting jules suite from nml files - copying with ${} files

### ISSUE THREAD

**Issue by nicgedney** [MetOffice/simulation-systems#88]
I'm trying to produce a rose suite (specifically the rose-app.conf file) but it needs to be automated and generic. Unfortunately the create_rose_app fails when it encounters ${} files. I can add a python script to deal with this, but is there a quick fix to deal with this?

**Comment by jennyhickson** [comment]
Hi Nic, I think you meant to put this in the discussion forum? I don't have an answer for you, but someone else might. Thanks

**Comment by nicgedney** [comment]
Oops. Apologies
